CREATE TABLE account(
    user_name VARCHAR(30) NOT NULL PRIMARY KEY,
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(60) NOT NULL,
    email VARCHAR(60) NOT NULL,
    password VARCHAR NOT NULL,
    trainer_name VARCHAR(30),
    FOREIGN KEY (trainer_name) REFERENCES account(user_name)
);

CREATE TABLE workout(
                        workout_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
                        workout_name varchar(100) NOT NULL,
                        workout_date DATE DEFAULT CURRENT_DATE NOT NULL
);
ALTER TABLE workout ADD COLUMN user_name VARCHAR(30);
ALTER TABLE workout ADD FOREIGN KEY (user_name) REFERENCES account(user_name);
ALTER TABLE WorkoutLift add column exercise_name VARCHAR(30);
ALTER table workoutlift add foreign key (exercise_name) REFERENCES exercise(exercise_name);

CREATE TABLE workout_lift(
                            workout_id integer,
                            FOREIGN KEY (workout_id) REFERENCES workout(workout_id),
                            lift_number integer,
                            exercise_name varchar,
                            CONSTRAINT pk_workoutLift PRIMARY KEY (workout_id, lift_number),
                            foreign key (exercise_name) REFERENCES exercise(exercise_name));

CREATE Table exercise(
                         exercise_name varchar(30) NOT NULL PRIMARY KEY,
                         primary_body_part varchar(30),
                         secondary_body_part varchar(30)
);



CREATE TABLE lift_set(
                        workout_id integer,
                        lift_number integer,
                        set_number integer,
                        weight integer,
                        reps integer,
                        FOREIGN KEY (workout_id, lift_number) REFERENCES workout_lift(workout_id, lift_number),
                        CONSTRAINT pk_liftSet PRIMARY KEY (workout_id, lift_number, set_number)
);

CREATE INDEX user_name_workout_idx ON workout (user_name);